hotfix(config) fix external ngx-wasm-rs builds
First this fixes the test cases and documentation as they were merged
(with edits), which wrongly assumed `NGX_CC_OPT` and `NGX_LD_OPT` were
digested by Nginx's `auto` scripts, they are not. They are derived from
`--with-{cc,ld}-opt` arguments.

Second, it moves defines and mandatory checks to `config` since we need
both even when `NGX_WASM_CARGO=0` and `auto/cargo` does not run.

The above fixes `NGX_WASM_CARGO=0` as a mean to *completely* disable
ngx-wasm-rs, as supported by Wasmer. This "mandatory={yes,no}" behavior
is tested for both Wasmer and V8 as well.

Finally, we also consider `NGX_WASM_CARGO` in the local development
environment freshness build script.

diff --git a/config b/config
--- a/config
+++ b/config
@@ -100,11 +100,17 @@ if [ "$ngx_wasm_cargo_lib_name" = ngx_wasm_rs ]; then
             ngx_wasm_runtime_path="$ngx_wasm_runtime_path $ngx_feature_path"
             ngx_wasm_runtime_libs="$ngx_wasm_runtime_libs $ngx_feature_libs"
         fi
+    fi
 
-    else
+    if echo -n "$ngx_wasm_runtime_libs\n$NGX_LD_OPT" | grep -q "ngx-wasm-rs"; then
         for d in $ngx_wasm_cargo_defines; do
             have=$d value=1 . auto/define
         done
+
+    elif [ $ngx_wasm_cargo_mandatory = yes ]; then
+        echo "$0: error: $ngx_addon_name with $NGX_WASM_RUNTIME requires lib$ngx_wasm_cargo_lib_name - aborting."
+        echo
+        exit 1
     fi
 fi
 
